<script setup>
import { defineProps } from 'vue';
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import { Head, Link, router, useForm } from "@inertiajs/vue3";
import Swal from 'sweetalert2';

const props = defineProps({
    records: Array,
});

const DeleteData = (id) => {
    Swal.fire({
        title: 'Are you sure?',
        text: 'This action cannot be undone!',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#d33',
        cancelButtonColor: '#3085d6',
        confirmButtonText: 'Yes, delete it!',
    }).then((result) => {
        if (result.isConfirmed) {
            router.delete(route('print.destroy', id), {
                preserveScroll: true,
                onSuccess: () => {
                    Swal.fire('Deleted!', 'The record has been deleted.', 'success');
                },
                onError: (errors) => {
                    Swal.fire('Error!', 'An error occurred while deleting the record.', 'error');
                },
            });
        }
    });
};
</script>

<template>
    <Head title="Show Record" />
    <AuthenticatedLayout>
        <div class="my-6 mx-6 space-y-6">

<div class="bg-white p-4 rounded-lg shadow-lg">
    <div class="mb-4 flex justify-between">
                    <h5 class="text-lg font-bold text-gray-800">Showing Records</h5>
                    <Link
                    :href="route('print.index')"
                    class="bg-red-600 text-white py-2 px-5 inline-block rounded mb-4"
                    >Back</Link>
                </div>
    <table class="w-full border border-gray-200 rounded-lg shadow">
        <thead>
            <tr class="bg-gray-100 text-gray-700 text-sm font-medium">
                <th class="py-2 px-4 text-left border-b border-r border-gray-200">First Name</th>
                <th class="py-2 px-4 text-left border-b border-r border-gray-200">Middle Name</th>
                <th class="py-2 px-4 text-left border-b border-r border-gray-200">Last Name</th>
                <th class="py-2 px-4 text-left border-b border-r border-gray-200">Generated By</th>
                <th class="py-2 px-4 text-left border-b border-r border-gray-200">Signatory</th>
                <th class="py-2 px-4 text-left border-b border-r border-gray-200">Position</th>
                <th class="py-2 px-4 text-left border-b border-r border-gray-200">Generated Date</th>
                <th class="py-2 px-4 text-left border-b border-r border-gray-200">Action</th>

            </tr>
        </thead>
        <tbody>
            <tr v-for="record in records" :key="record.id">
                <td class="py-2 px-4 border-b border-r border-gray-200">{{ record.firstname }}</td>
                <td class="py-2 px-4 border-b border-r border-gray-200">{{ record.middlename }}</td>
                <td class="py-2 px-4 border-b border-r border-gray-200">{{ record.lastname }}</td>
                <td class="py-2 px-4 border-b border-r border-gray-200">{{ record.generated_by }}</td>
                <td class="py-2 px-4 border-b border-r border-gray-200">{{ record.signatory }}</td>
                <td class="py-2 px-4 border-b border-r border-gray-200">{{ record.position }}</td>
                <td class="py-2 px-4 border-b border-r border-gray-200">{{ record.created_at }}</td>
                <td class="py-2 px-4 border-b border-r border-gray-200">
    <button
        @click="DeleteData(record.id)"
        class="px-2 py-1 text-sm bg-red-600 text-white p-3 rounded"
    >
        Delete
    </button>
</td>


            </tr>
        </tbody>
    </table>
</div>
</div>
</AuthenticatedLayout>

</template>
